version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.53
    steps:
      - checkout
      - run:
          name: Submodules init
          command: git submodule init
      - run:
          name: Submodule update
          command: git submodule update --remote
      - run:
          name: Build
          command: BASE_URL="/scs/`echo $CIRCLE_PULL_REQUEST | rev | cut -d'/' -f1 | rev`/"; hugo -v -b $BASE_URL
      - run:
          name: Deploy built docs
          command: |
            PR_NUMBER=`echo $CIRCLE_PULL_REQUEST | rev | cut -d'/' -f1 | rev`; scp -r ./public http@it-01.informo.network:/srv/http/specs-staging/public/scs/$PR_NUMBER

