version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.53
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote
      - run: BASE_URL="/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/public/"; hugo -v -b $BASE_URL
      - store_artifacts:
          path: public
      - run:
          name: "Doc build is available at:"
          command: DOCS_URL="/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/public/"; echo $DOCS_URL
