version: 2.1

orbs:
  hugo: felicianotech/hugo@0.0.5

jobs:
  build_specs:
    machine:
      enabled: true
    steps:
      - hugo/install:
        version: 0.53
      - checkout
      - run: hugo build

